from fastapi import APIRouter, HTTPException, Body
from pydantic import BaseModel
from langgraph.types import Command
from app.graphs.loan_agent_graph import loan_app 

router = APIRouter()

class ApplyLoan(BaseModel):
    full_name: str
    id_card_num: str
    loan_amount: float      # Changed from str to float
    loan_term_months: int   # Changed from str to int
    monthly_income: float   # Changed from str to float
    loan_purpose: str
    loan_reason: str

@router.post("/apply")
async def apply_loan(data: ApplyLoan):
    config = {"configurable": {"thread_id": data.id_card_num}}

    initial_state = {
        "full_name": data.full_name,
        "id_card_num": data.id_card_num,
        "loan_amount": data.loan_amount,
        "loan_term_months": data.loan_term_months,
        "monthly_income": data.monthly_income,
        "loan_purpose": data.loan_purpose,
        "loan_reason": data.loan_reason,
        "messages": [] # Crucial for the graph to have a message history key
    }
    
    final_state = loan_app.invoke(initial_state, config)
    
    snapshot = loan_app.get_state(config)

    if snapshot.next:
        return {
            "loan_id": final_state.get("loan_id"), # Generated by your planner
            "status": "pending_human_review",
            "message": "Your application requires manual oversight.",
            "credit_score": final_state.get("credit_score")
        }

    return {
        "loan_id": final_state.get("loan_id"),
        "status": final_state.get("loan_status"),   
        "message": final_state.get("notification_message")
    }


@router.post("/review")
async def review_loan(id_card_num: str = Body(..., embed=True), decision: str = Body(..., embed=True))-> dict:
    """Allows a Credit Officer to resume a paused loan graph."""
    config = {"configurable": {"thread_id": id_card_num}}
    
    final_state = loan_app.invoke(Command(resume=decision), config)
    return {"status": final_state.get("loan_status"), "message": final_state.get("notification_message")}

